.TH "lib/RTC/examples/DS3231_Alarms/Visual Micro/.DS3231_Alarms.vsarduino.h" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/RTC/examples/DS3231_Alarms/Visual Micro/.DS3231_Alarms.vsarduino.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <arduino\&.h>\fP
.br
\fC#include <pins_arduino\&.h>\fP
.br
\fC#include <DS3231_Alarms\&.ino>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__AVR_ATmega2560__\fP"
.br
.ti -1c
.RI "#define \fBARDUINO\fP   161"
.br
.ti -1c
.RI "#define \fBARDUINO_MAIN\fP"
.br
.ti -1c
.RI "#define \fB__AVR__\fP"
.br
.ti -1c
.RI "#define \fB__avr__\fP"
.br
.ti -1c
.RI "#define \fBF_CPU\fP   16000000L"
.br
.ti -1c
.RI "#define \fB__cplusplus\fP"
.br
.ti -1c
.RI "#define \fBGCC_VERSION\fP   40801"
.br
.ti -1c
.RI "#define \fBARDUINO_ARCH_AVR\fP"
.br
.ti -1c
.RI "#define \fBARDUINO_AVR_MEGA2560\fP"
.br
.ti -1c
.RI "#define \fB__inline__\fP"
.br
.ti -1c
.RI "#define \fB__asm__\fP(x)"
.br
.ti -1c
.RI "#define \fB__extension__\fP"
.br
.ti -1c
.RI "#define \fB__inline__\fP"
.br
.ti -1c
.RI "#define \fB__volatile__\fP"
.br
.ti -1c
.RI "#define \fBGCC_VERSION\fP   40801"
.br
.ti -1c
.RI "#define \fBvolatile\fP(va_arg)"
.br
.ti -1c
.RI "#define \fB__builtin_va_start\fP"
.br
.ti -1c
.RI "#define \fB__builtin_va_end\fP"
.br
.ti -1c
.RI "#define \fB__attribute__\fP(x)"
.br
.ti -1c
.RI "#define \fBNOINLINE\fP   \fB__attribute__\fP((noinline))"
.br
.ti -1c
.RI "#define \fBprog_void\fP"
.br
.ti -1c
.RI "#define \fBPGM_VOID_P\fP   int"
.br
.ti -1c
.RI "#define \fBNEW_H\fP"
.br
.ti -1c
.RI "#define \fBF\fP(string_literal)   ((const \fBPROGMEM\fP char *)(string_literal))"
.br
.ti -1c
.RI "#define \fBcli\fP()"
.br
.ti -1c
.RI "#define \fBpgm_read_byte\fP(address_short)"
.br
.ti -1c
.RI "#define \fBpgm_read_word\fP(address_short)"
.br
.ti -1c
.RI "#define \fBpgm_read_word2\fP(address_short)"
.br
.ti -1c
.RI "#define \fBdigitalPinToPort\fP(P)"
.br
.ti -1c
.RI "#define \fBdigitalPinToBitMask\fP(P)"
.br
.ti -1c
.RI "#define \fBdigitalPinToTimer\fP(P)"
.br
.ti -1c
.RI "#define \fBanalogInPinToBit\fP(P)"
.br
.ti -1c
.RI "#define \fBportOutputRegister\fP(P)"
.br
.ti -1c
.RI "#define \fBportInputRegister\fP(P)"
.br
.ti -1c
.RI "#define \fBportModeRegister\fP(P)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fB__builtin_va_list\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBbyte\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__cxa_pure_virtual\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __asm__(x)"

.PP
Definition at line 24 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define __attribute__(x)"

.PP
Definition at line 38 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define __AVR__"

.PP
Definition at line 16 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define __avr__"

.PP
Definition at line 17 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define __AVR_ATmega2560__"

.PP
Definition at line 13 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define __builtin_va_end"

.PP
Definition at line 36 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define __builtin_va_start"

.PP
Definition at line 35 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define __cplusplus"

.PP
Definition at line 19 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define __extension__"

.PP
Definition at line 25 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define __inline__"

.PP
Definition at line 28 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define __inline__"

.PP
Definition at line 28 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define __volatile__"

.PP
Definition at line 30 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define analogInPinToBit(P)"

.PP
Definition at line 77 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define ARDUINO   161"

.PP
Definition at line 14 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define ARDUINO_ARCH_AVR"

.PP
Definition at line 21 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define ARDUINO_AVR_MEGA2560"

.PP
Definition at line 22 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define ARDUINO_MAIN"

.PP
Definition at line 15 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define cli()"

.PP
Definition at line 70 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define digitalPinToBitMask(P)"

.PP
Definition at line 75 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define digitalPinToPort(P)"

.PP
Definition at line 74 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define digitalPinToTimer(P)"

.PP
Definition at line 76 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define F(string_literal)   ((const \fBPROGMEM\fP char *)(string_literal))"

.PP
Definition at line 68 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define F_CPU   16000000L"

.PP
Definition at line 18 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define GCC_VERSION   40801"

.PP
Definition at line 31 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define GCC_VERSION   40801"

.PP
Definition at line 31 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define NEW_H"

.PP
Definition at line 42 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define NOINLINE   \fB__attribute__\fP((noinline))"

.PP
Definition at line 39 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define pgm_read_byte(address_short)"

.PP
Definition at line 71 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define pgm_read_word(address_short)"

.PP
Definition at line 72 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define pgm_read_word2(address_short)"

.PP
Definition at line 73 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define PGM_VOID_P   int"

.PP
Definition at line 41 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define portInputRegister(P)"

.PP
Definition at line 79 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define portModeRegister(P)"

.PP
Definition at line 80 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define portOutputRegister(P)"

.PP
Definition at line 78 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define prog_void"

.PP
Definition at line 40 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "#define volatile(va_arg)"

.PP
Definition at line 32 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fB__builtin_va_list\fP"

.PP
Definition at line 34 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SS "typedef unsigned char \fBbyte\fP"

.PP
Definition at line 60 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void __cxa_pure_virtual ()"

.PP
Definition at line 61 of file \&.DS3231_Alarms\&.vsarduino\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
