.TH "Backup/test Directory Reference" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backup/test Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmq2misterio\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBecho_server\&.cpp\fP"
.br
.in -1c
