.TH "Backup/CitzenProject/Citizen-Sensor/stationary/XBeeScripts Directory Reference" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backup/CitzenProject/Citizen-Sensor/stationary/XBeeScripts Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpachube_functions\&.php\fP"
.br
.ti -1c
.RI "file \fBwt\&.php\fP"
.br
.ti -1c
.RI "file \fBxbeeupdate\&.php\fP"
.br
.in -1c
