.TH "CS_MQ7" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CS_MQ7 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CS_MQ7\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCS_MQ7\fP (int CoTogPin, int CoIndicatorPin)"
.br
.ti -1c
.RI "\fBCS_MQ7\fP (int CoTogPin)"
.br
.ti -1c
.RI "void \fBCoPwrCycler\fP ()"
.br
.ti -1c
.RI "boolean \fBcurrentState\fP ()"
.br
.ti -1c
.RI "\fBCS_MQ7\fP (int CoTogPin, int CoIndicatorPin)"
.br
.ti -1c
.RI "\fBCS_MQ7\fP (int CoTogPin)"
.br
.ti -1c
.RI "void \fBCoPwrCycler\fP ()"
.br
.ti -1c
.RI "boolean \fBcurrentState\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBtime\fP"
.br
.ti -1c
.RI "unsigned long \fBcurrTime\fP"
.br
.ti -1c
.RI "unsigned long \fBprevTime\fP"
.br
.ti -1c
.RI "unsigned long \fBcurrCoPwrTimer\fP"
.br
.ti -1c
.RI "boolean \fBCoPwrState\fP"
.br
.ti -1c
.RI "boolean \fBindicatorAttached\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file CS_MQ7\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CS_MQ7::CS_MQ7 (int CoTogPin, int CoIndicatorPin)"

.PP
Definition at line 22 of file CS_MQ7\&.cpp\&.
.SS "CS_MQ7::CS_MQ7 (int CoTogPin)"

.PP
Definition at line 39 of file CS_MQ7\&.cpp\&.
.SS "CS_MQ7::CS_MQ7 (int CoTogPin, int CoIndicatorPin)"

.SS "CS_MQ7::CS_MQ7 (int CoTogPin)"

.SH "Member Function Documentation"
.PP 
.SS "void CS_MQ7::CoPwrCycler ()"

.PP
Definition at line 54 of file CS_MQ7\&.cpp\&.
.SS "void CS_MQ7::CoPwrCycler ()"

.SS "boolean CS_MQ7::currentState ()"

.PP
Definition at line 72 of file CS_MQ7\&.cpp\&.
.SS "boolean CS_MQ7::currentState ()"

.SH "Member Data Documentation"
.PP 
.SS "boolean CS_MQ7::CoPwrState"

.PP
Definition at line 29 of file CS_MQ7\&.h\&.
.SS "unsigned long CS_MQ7::currCoPwrTimer"

.PP
Definition at line 27 of file CS_MQ7\&.h\&.
.SS "unsigned long CS_MQ7::currTime"

.PP
Definition at line 25 of file CS_MQ7\&.h\&.
.SS "boolean CS_MQ7::indicatorAttached"

.PP
Definition at line 30 of file CS_MQ7\&.h\&.
.SS "unsigned long CS_MQ7::prevTime"

.PP
Definition at line 26 of file CS_MQ7\&.h\&.
.SS "unsigned long CS_MQ7::time"

.PP
Definition at line 24 of file CS_MQ7\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
