.TH "lib/DHT/src/dht.h" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/DHT/src/dht.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'WProgram\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDHT\fP"
.br
.ti -1c
.RI "class \fBInterruptLock\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG_PRINTER\fP   Serial"
.br
.ti -1c
.RI "#define \fBDEBUG_PRINT\fP(\&.\&.\&.)   { }"
.br
.ti -1c
.RI "#define \fBDEBUG_PRINTLN\fP(\&.\&.\&.)   { }"
.br
.ti -1c
.RI "#define \fBDHT11\fP   11"
.br
.ti -1c
.RI "#define \fBDHT22\fP   22"
.br
.ti -1c
.RI "#define \fBDHT21\fP   21"
.br
.ti -1c
.RI "#define \fBAM2301\fP   21"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AM2301   21"

.PP
Definition at line 35 of file dht\&.h\&.
.SS "#define DEBUG_PRINT( \&.\&.\&.)   { }"

.PP
Definition at line 27 of file dht\&.h\&.
.SS "#define DEBUG_PRINTER   Serial"

.PP
Definition at line 20 of file dht\&.h\&.
.SS "#define DEBUG_PRINTLN( \&.\&.\&.)   { }"

.PP
Definition at line 28 of file dht\&.h\&.
.SS "#define DHT11   11"

.PP
Definition at line 32 of file dht\&.h\&.
.SS "#define DHT21   21"

.PP
Definition at line 34 of file dht\&.h\&.
.SS "#define DHT22   22"

.PP
Definition at line 33 of file dht\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
