.TH "DHT" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DHT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dht\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDHT\fP (uint8_t pin, uint8_t type, uint8_t count=6)"
.br
.ti -1c
.RI "void \fBbegin\fP (void)"
.br
.ti -1c
.RI "float \fBreadTemperature\fP (bool S=false, bool force=false)"
.br
.ti -1c
.RI "float \fBconvertCtoF\fP (float)"
.br
.ti -1c
.RI "float \fBconvertFtoC\fP (float)"
.br
.ti -1c
.RI "float \fBcomputeHeatIndex\fP (float temperature, float percentHumidity, bool isFahrenheit=true)"
.br
.ti -1c
.RI "float \fBreadHumidity\fP (bool force=false)"
.br
.ti -1c
.RI "boolean \fBread\fP (bool force=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file dht\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DHT::DHT (uint8_t pin, uint8_t type, uint8_t count = \fC6\fP)"

.PP
Definition at line 11 of file dht\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void DHT::begin (void)"

.PP
Definition at line 24 of file dht\&.cpp\&.
.SS "float DHT::computeHeatIndex (float temperature, float percentHumidity, bool isFahrenheit = \fCtrue\fP)"

.PP
Definition at line 94 of file dht\&.cpp\&.
.SS "float DHT::convertCtoF (float c)"

.PP
Definition at line 65 of file dht\&.cpp\&.
.SS "float DHT::convertFtoC (float f)"

.PP
Definition at line 69 of file dht\&.cpp\&.
.SS "boolean DHT::read (bool force = \fCfalse\fP)"

.PP
Definition at line 125 of file dht\&.cpp\&.
.SS "float DHT::readHumidity (bool force = \fCfalse\fP)"

.PP
Definition at line 73 of file dht\&.cpp\&.
.SS "float DHT::readTemperature (bool S = \fCfalse\fP, bool force = \fCfalse\fP)"

.PP
Definition at line 36 of file dht\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
