.TH "dht" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dht \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dht\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdht\fP ()"
.br
.ti -1c
.RI "int8_t \fBread11\fP (uint8_t pin)"
.br
.ti -1c
.RI "int8_t \fBread\fP (uint8_t pin)"
.br
.ti -1c
.RI "int8_t \fBread21\fP (uint8_t pin)"
.br
.ti -1c
.RI "int8_t \fBread22\fP (uint8_t pin)"
.br
.ti -1c
.RI "int8_t \fBread33\fP (uint8_t pin)"
.br
.ti -1c
.RI "int8_t \fBread44\fP (uint8_t pin)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBhumidity\fP"
.br
.ti -1c
.RI "double \fBtemperature\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file dht\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dht::dht ()\fC [inline]\fP"

.PP
Definition at line 51 of file dht\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int8_t dht::read (uint8_t pin)"

.PP
Definition at line 69 of file dht\&.cpp\&.
.SS "int8_t dht::read11 (uint8_t pin)"

.PP
Definition at line 48 of file dht\&.cpp\&.
.SS "int8_t dht::read21 (uint8_t pin)\fC [inline]\fP"

.PP
Definition at line 62 of file dht\&.h\&.
.SS "int8_t dht::read22 (uint8_t pin)\fC [inline]\fP"

.PP
Definition at line 63 of file dht\&.h\&.
.SS "int8_t dht::read33 (uint8_t pin)\fC [inline]\fP"

.PP
Definition at line 64 of file dht\&.h\&.
.SS "int8_t dht::read44 (uint8_t pin)\fC [inline]\fP"

.PP
Definition at line 65 of file dht\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double dht::humidity"

.PP
Definition at line 65 of file dht\&.h\&.
.SS "double dht::temperature"

.PP
Definition at line 68 of file dht\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
