.TH "lib/DHT/dht.h" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/DHT/dht.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <WProgram\&.h>\fP
.br
\fC#include <pins_arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdht\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDHT_LIB_VERSION\fP   '0\&.1\&.21'"
.br
.ti -1c
.RI "#define \fBDHTLIB_OK\fP   0"
.br
.ti -1c
.RI "#define \fBDHTLIB_ERROR_CHECKSUM\fP   \-1"
.br
.ti -1c
.RI "#define \fBDHTLIB_ERROR_TIMEOUT\fP   \-2"
.br
.ti -1c
.RI "#define \fBDHTLIB_ERROR_CONNECT\fP   \-3"
.br
.ti -1c
.RI "#define \fBDHTLIB_ERROR_ACK_L\fP   \-4"
.br
.ti -1c
.RI "#define \fBDHTLIB_ERROR_ACK_H\fP   \-5"
.br
.ti -1c
.RI "#define \fBDHTLIB_DHT11_WAKEUP\fP   18"
.br
.ti -1c
.RI "#define \fBDHTLIB_DHT_WAKEUP\fP   1"
.br
.ti -1c
.RI "#define \fBDHTLIB_DHT11_LEADING_ZEROS\fP   1"
.br
.ti -1c
.RI "#define \fBDHTLIB_DHT_LEADING_ZEROS\fP   6"
.br
.ti -1c
.RI "#define \fBDHTLIB_TIMEOUT\fP   1000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DHT_LIB_VERSION   '0\&.1\&.21'"

.PP
Definition at line 22 of file dht\&.h\&.
.SS "#define DHTLIB_DHT11_LEADING_ZEROS   1"

.PP
Definition at line 34 of file dht\&.h\&.
.SS "#define DHTLIB_DHT11_WAKEUP   18"

.PP
Definition at line 31 of file dht\&.h\&.
.SS "#define DHTLIB_DHT_LEADING_ZEROS   6"

.PP
Definition at line 35 of file dht\&.h\&.
.SS "#define DHTLIB_DHT_WAKEUP   1"

.PP
Definition at line 32 of file dht\&.h\&.
.SS "#define DHTLIB_ERROR_ACK_H   \-5"

.PP
Definition at line 29 of file dht\&.h\&.
.SS "#define DHTLIB_ERROR_ACK_L   \-4"

.PP
Definition at line 28 of file dht\&.h\&.
.SS "#define DHTLIB_ERROR_CHECKSUM   \-1"

.PP
Definition at line 25 of file dht\&.h\&.
.SS "#define DHTLIB_ERROR_CONNECT   \-3"

.PP
Definition at line 27 of file dht\&.h\&.
.SS "#define DHTLIB_ERROR_TIMEOUT   \-2"

.PP
Definition at line 26 of file dht\&.h\&.
.SS "#define DHTLIB_OK   0"

.PP
Definition at line 24 of file dht\&.h\&.
.SS "#define DHTLIB_TIMEOUT   1000"

.PP
Definition at line 43 of file dht\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
