.TH "Backup/test/echo_server.cpp" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backup/test/echo_server.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <SoftwareSerial\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBTSerial\fP   Serial1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.ti -1c
.RI "void \fBloop\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "String \fBcommand\fP = ''"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BTSerial   Serial1"

.PP
Definition at line 13 of file echo_server\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "void loop ()"

.PP
Definition at line 28 of file echo_server\&.cpp\&.
.SS "void setup ()"

.PP
Definition at line 20 of file echo_server\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "String command = ''"

.PP
Definition at line 16 of file echo_server\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
