.TH "Backup/HC05-master/HC05.h" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backup/HC05-master/HC05.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <inttypes\&.h>\fP
.br
\fC#include <Stream\&.h>\fP
.br
\fC#include <SoftwareSerial\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHC05\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHC05_STATE_PIN\fP"
.br
.ti -1c
.RI "#define \fBHC05_HW_SERIAL_PORT\fP   Serial1"
.br
.ti -1c
.RI "#define \fBHC05_SOFTWARE_SERIAL\fP"
.br
.ti -1c
.RI "#define \fBDEBUG_HC05\fP"
.br
.ti -1c
.RI "#define \fBDEBUG_PORT\fP   Serial"
.br
.ti -1c
.RI "#define \fBDEBUG_BEGIN\fP(baud)   DEBUG_PORT\&.begin(baud)"
.br
.ti -1c
.RI "#define \fBDEBUG_WRITE\fP(\&.\&.\&.)   DEBUG_PORT\&.write(__VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBDEBUG_PRINT\fP(\&.\&.\&.)   DEBUG_PORT\&.print(__VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBDEBUG_PRINTLN\fP(\&.\&.\&.)   DEBUG_PORT\&.println(__VA_ARGS__)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBHC05\fP \fBbtSerial\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG_BEGIN(baud)   DEBUG_PORT\&.begin(baud)"

.PP
Definition at line 58 of file HC05\&.h\&.
.SS "#define DEBUG_HC05"

.PP
Definition at line 48 of file HC05\&.h\&.
.SS "#define DEBUG_PORT   Serial"

.PP
Definition at line 55 of file HC05\&.h\&.
.SS "#define DEBUG_PRINT( \&.\&.\&.)   DEBUG_PORT\&.print(__VA_ARGS__)"

.PP
Definition at line 60 of file HC05\&.h\&.
.SS "#define DEBUG_PRINTLN( \&.\&.\&.)   DEBUG_PORT\&.println(__VA_ARGS__)"

.PP
Definition at line 61 of file HC05\&.h\&.
.SS "#define DEBUG_WRITE( \&.\&.\&.)   DEBUG_PORT\&.write(__VA_ARGS__)"

.PP
Definition at line 59 of file HC05\&.h\&.
.SS "#define HC05_HW_SERIAL_PORT   Serial1"

.PP
Definition at line 41 of file HC05\&.h\&.
.SS "#define HC05_SOFTWARE_SERIAL"

.PP
Definition at line 47 of file HC05\&.h\&.
.SS "#define HC05_STATE_PIN"

.PP
Definition at line 34 of file HC05\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "\fBHC05\fP btSerial"

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
