.TH "Backup/HC05-master/HC05.cpp" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backup/HC05-master/HC05.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <HC05\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_btSerial\fP   \fBHC05_HW_SERIAL_PORT\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _btSerial   \fBHC05_HW_SERIAL_PORT\fP"

.PP
Definition at line 11 of file HC05\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
