.TH "InterruptLock" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterruptLock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dht\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterruptLock\fP ()"
.br
.ti -1c
.RI "\fB~InterruptLock\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file dht\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InterruptLock::InterruptLock ()\fC [inline]\fP"

.PP
Definition at line 65 of file dht\&.h\&.
.SS "InterruptLock::~InterruptLock ()\fC [inline]\fP"

.PP
Definition at line 69 of file dht\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
