.TH "lib/LDR/src/ldr.hpp" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/LDR/src/ldr.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBldr\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
