.TH "lib/LogManager/src/LogManager.cpp" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/LogManager/src/LogManager.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include 'LogManager\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
