.TH "LogManager" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LogManager\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogManager\fP (uint8_t cspin, uint8_t verbose=QUIET, const char *fileName='data\&.csv')"
.br
.ti -1c
.RI "uint8_t \fBstartLogManager\fP ()"
.br
.ti -1c
.RI "uint16_t \fBprintln\fP (const String message)"
.br
.ti -1c
.RI "String \fBreadln\fP ()"
.br
.ti -1c
.RI "void \fBgotoTop\fP ()"
.br
.ti -1c
.RI "void \fBgotoEnd\fP ()"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fB_CSpin\fP"
.br
.ti -1c
.RI "uint8_t \fB_VERBOSE\fP"
.br
.ti -1c
.RI "File \fB_LOG\fP"
.br
.ti -1c
.RI "String \fB_message\fP"
.br
.ti -1c
.RI "const char * \fB_fileName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file LogManager\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LogManager::LogManager (uint8_t cspin, uint8_t verbose = \fCQUIET\fP, const char * fileName = \fC'data\&.csv'\fP)\fC [inline]\fP"

.PP
Definition at line 27 of file LogManager\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void LogManager::close ()"

.PP
Definition at line 94 of file LogManager\&.cpp\&.
.SS "void LogManager::flush ()"

.PP
Definition at line 90 of file LogManager\&.cpp\&.
.SS "void LogManager::gotoEnd ()"

.PP
Definition at line 84 of file LogManager\&.cpp\&.
.SS "void LogManager::gotoTop ()"

.PP
Definition at line 78 of file LogManager\&.cpp\&.
.SS "uint16_t LogManager::println (const String message)"

.PP
Definition at line 38 of file LogManager\&.cpp\&.
.SS "String LogManager::readln ()"

.PP
Definition at line 57 of file LogManager\&.cpp\&.
.SS "uint8_t LogManager::startLogManager ()"

.PP
Definition at line 4 of file LogManager\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t LogManager::_CSpin\fC [protected]\fP"

.PP
Definition at line 42 of file LogManager\&.hpp\&.
.SS "const char* LogManager::_fileName\fC [protected]\fP"

.PP
Definition at line 45 of file LogManager\&.hpp\&.
.SS "File LogManager::_LOG\fC [protected]\fP"

.PP
Definition at line 43 of file LogManager\&.hpp\&.
.SS "String LogManager::_message\fC [protected]\fP"

.PP
Definition at line 44 of file LogManager\&.hpp\&.
.SS "uint8_t LogManager::_VERBOSE\fC [protected]\fP"

.PP
Definition at line 42 of file LogManager\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
