.TH "lib/LogManager/src/LogManager.hpp" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/LogManager/src/LogManager.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <SPI\&.h>\fP
.br
\fC#include <SD\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogManager\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBverboseType\fP : const uint8_t "
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBverboseType\fP : const uint8_t"

.PP
Definition at line 9 of file LogManager\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
