.TH "src/main.hpp" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'dht\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdhtDebug\fP (\fBdht\fP Sensor, uint8_t \fBDHT11_PIN\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dhtDebug (\fBdht\fP Sensor, uint8_t DHT11_PIN)"

.PP
Definition at line 8 of file main\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
