.TH "src/main.hpp" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <\&.\&./lib/DHT/src/dht\&.h>\fP
.br
\fC#include <ldr\&.hpp>\fP
.br
\fC#include <\&.\&./lib/MQ\-Sensor/src/MQSensor\&.hpp>\fP
.br
\fC#include <\&.\&./lib/PrintManager/src/PrintManager\&.hpp>\fP
.br
\fC#include <\&.\&./lib/RTC/src/RtcDS1307\&.h>\fP
.br
\fC#include <Wire\&.h>\fP
.br
\fC#include <TinyGPS++\&.h>\fP
.br
\fC#include <SPI\&.h>\fP
.br
\fC#include <SD\&.h>\fP
.br
\fC#include <EEPROM\&.h>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBdataLocation\fP : const uint8_t "
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdisplayInfo\fP ()"
.br
.ti -1c
.RI "template<class T > int \fBEEPROM_writeAnything\fP (int ee, const T &value)"
.br
.ti -1c
.RI "template<class T > int \fBEEPROM_readAnything\fP (int ee, T &value)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBDHT11_PIN\fP = 5"
.br
.ti -1c
.RI "const uint8_t \fBDHTTYPE\fP = \fBDHT11\fP"
.br
.ti -1c
.RI "const uint8_t \fBLDR_PIN\fP = A7"
.br
.ti -1c
.RI "const uint8_t \fBHOME_LAT\fP = 0 * sizeof(double)"
.br
.ti -1c
.RI "const uint8_t \fBHOME_LON\fP = 1 * sizeof(double)"
.br
.ti -1c
.RI "const uint8_t \fBMQ7_PIN\fP = A1"
.br
.ti -1c
.RI "const uint8_t \fBMQ3_PIN\fP = A2"
.br
.ti -1c
.RI "\fBDHT\fP \fBdht\fP (\fBDHT11_PIN\fP, \fBDHTTYPE\fP)"
.br
.ti -1c
.RI "\fBldr\fP \fBLDRSensor\fP = \fBldr\fP(\fBLDR_PIN\fP)"
.br
.ti -1c
.RI "\fBRtcDS1307\fP< TwoWire > \fBRtc\fP (Wire)"
.br
.ti -1c
.RI "\fBTinyGPSPlus\fP \fBGPS_Module\fP"
.br
.ti -1c
.RI "\fBMQ7\fP \fBMQ7_Sensor\fP = \fBMQ7\fP(\fBMQ7_PIN\fP)"
.br
.ti -1c
.RI "\fBMQ3\fP \fBMQ3_Sensor\fP = \fBMQ3\fP(\fBMQ3_PIN\fP)"
.br
.ti -1c
.RI "\fBLogManager\fP \fBSD_Loger\fP = \fBLogManager\fP(52, VERBOSE, 'weater\&.log')"
.br
.ti -1c
.RI "\fBPrintManager\fP \fBPrint_Manager\fP = \fBPrintManager\fP(&Serial1, &\fBSD_Loger\fP)"
.br
.ti -1c
.RI "double \fBtemporaryData\fP [DATA_SIZE]"
.br
.ti -1c
.RI "\fBRtcDateTime\fP \fBclockTime\fP"
.br
.ti -1c
.RI "bool \fBclockUpdate\fP = true"
.br
.ti -1c
.RI "File \fBmyFile\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBdataLocation\fP : const uint8_t"

.PP
Definition at line 31 of file main\&.hpp\&.
.SH "Function Documentation"
.PP 
.SS "void displayInfo ()"

.PP
Definition at line 73 of file main\&.hpp\&.
.SS "template<class T > int EEPROM_readAnything (int ee, T & value)"

.PP
Definition at line 123 of file main\&.hpp\&.
.SS "template<class T > int EEPROM_writeAnything (int ee, const T & value)"

.PP
Definition at line 114 of file main\&.hpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBRtcDateTime\fP clockTime"

.PP
Definition at line 69 of file main\&.hpp\&.
.SS "bool clockUpdate = true"

.PP
Definition at line 70 of file main\&.hpp\&.
.SS "\fBDHT\fP dht(\fBDHT11_PIN\fP, \fBDHTTYPE\fP)"

.SS "const uint8_t DHT11_PIN = 5"

.PP
Definition at line 22 of file main\&.hpp\&.
.SS "const uint8_t DHTTYPE = \fBDHT11\fP"

.PP
Definition at line 23 of file main\&.hpp\&.
.SS "\fBTinyGPSPlus\fP GPS_Module"

.PP
Definition at line 55 of file main\&.hpp\&.
.SS "const uint8_t HOME_LAT = 0 * sizeof(double)"

.PP
Definition at line 25 of file main\&.hpp\&.
.SS "const uint8_t HOME_LON = 1 * sizeof(double)"

.PP
Definition at line 25 of file main\&.hpp\&.
.SS "const uint8_t LDR_PIN = A7"

.PP
Definition at line 24 of file main\&.hpp\&.
.SS "\fBldr\fP LDRSensor = \fBldr\fP(\fBLDR_PIN\fP)"

.PP
Definition at line 53 of file main\&.hpp\&.
.SS "const uint8_t MQ3_PIN = A2"

.PP
Definition at line 27 of file main\&.hpp\&.
.SS "\fBMQ3\fP MQ3_Sensor = \fBMQ3\fP(\fBMQ3_PIN\fP)"

.PP
Definition at line 57 of file main\&.hpp\&.
.SS "const uint8_t MQ7_PIN = A1"

.PP
Definition at line 26 of file main\&.hpp\&.
.SS "\fBMQ7\fP MQ7_Sensor = \fBMQ7\fP(\fBMQ7_PIN\fP)"

.PP
Definition at line 56 of file main\&.hpp\&.
.SS "File myFile"

.PP
Definition at line 71 of file main\&.hpp\&.
.SS "\fBPrintManager\fP Print_Manager = \fBPrintManager\fP(&Serial1, &\fBSD_Loger\fP)"

.PP
Definition at line 64 of file main\&.hpp\&.
.SS "\fBRtcDS1307\fP<TwoWire> Rtc(Wire)"

.SS "\fBLogManager\fP SD_Loger = \fBLogManager\fP(52, VERBOSE, 'weater\&.log')"

.PP
Definition at line 61 of file main\&.hpp\&.
.SS "double temporaryData[DATA_SIZE]"

.PP
Definition at line 68 of file main\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
