.TH "md__r_e_a_d_m_e__p_t_b_r" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e__p_t_b_r \- Arduino Libraries 
\fC\fP \fC\fP \fC\fP \fC\fP \fC\fP
.PP
This is the repository for the \fBCanary\fP project\&.
.PP
In this directory you can find the libraries \fCHbridge\fP, used to control \fBH Bridge\fP circuits and \fCLineController\fP, used to read \fBLine Reader\fP circuits, ready or \fIDIY\fP ones\&.
.PP
Neste diretório se encontram as bibliotecas \fCHbridge\fP, para controle de circuitos \fBPonte H\fP e \fCLineController\fP, para leitura de circuitos de \fBDetecção de Linha\fP, podendo ser um pronto ou \fIDIY\fP\&.
.PP
.SS "Table of Contents"
.PP
English Português  - \fCBackground\fP - \fCHistórico\fP - \fCInstall\fP - \fCInstalação\fP - \fCUsage\fP - \fCUso\fP - \fCContribute\fP - \fCContribuir\fP - \fCLicense\fP - \fCLicensa\fP - - \fCOnde Comprar\fP 
.SS "Background"
.PP
These libraries were initially created for the discipline Programming Languages III, lessioned by professor Cristian Pagot in late 2016 in Universidade Federal da Paraíba, Brazil\&. Currently it has continuous support\&.
.PP
.SS "Install"
.PP
More information can be found in https://www.arduino.cc/en/Guide/Libraries 
.SS "Windows"
.PP
Copy the desired library to \fCLibraries\fP inside the \fCArduino\fP folder in \fCMy Documents\fP\&.
.PP
.SS "Linux"
.PP
Copy the desired library to \fCLibraries\fP inside the Arduino IDE instalation folder\&.
.PP
.SS "Atom"
.PP
Copy the desired library to the \fCLib\fP folder in the compilation directory\&.
.PP
.SS "Usage"
.PP
Follow each library \fBREADME\fP\&.
.IP "\(bu" 2
/Hbridge/docs/README\&.md 'Hbridge'
.IP "\(bu" 2
/LineController/docs/README\&.md 'LineController'
.PP
.PP
.SS "Contribute"
.PP
Feel free to copy and improve this library, if necessary, you may \fCreport a problem\fP\&. Doubts and suggestions, contact me at danppoltronieri@gmail.com\&.
.PP
See \fBthe contribute file\fP!
.PP
PRs accepted\&.
.PP
.SS "License"
.PP
[MIT © Richard McRichface\&.](LICENSE)
.PP
.SS "Histórico"
.PP
Essas bibliotecas foram criadas inicialmente para a disciplina de Linguagem de Programação III ministrada pelo professor Cristian Pagot no período 2016\&.1 da Universidade Federal da Paraíba\&. Atualmente ela possui suporte contínuo\&.
.PP
.SS "Instalação"
.PP
Mais informações podem ser encontradas em https://www.arduino.cc/en/Guide/Libraries 
.SS "Windows"
.PP
Copie a biblioteca desejada para a pasta \fCLibraries\fP dentro da pasta \fCArduino\fP em \fCMeus Documentos\fP\&.
.PP
.SS "Linux"
.PP
Copie a biblioteca desejada para a pasta \fCLibraries\fP dentro do diretório de instalação da IDE Arduino\&.
.PP
.SS "Atom"
.PP
Copie a biblioteca desejada para a pasta \fCLib\fP dentro do diretório de compilação\&.
.PP
.SS "Uso"
.PP
Siga o \fBREADME\fP de cada biblioteca\&. \fCHbridge\fP
.PP
.SS "Contribuir"
.PP
Sinta-se livre para copiar e melhorar essa biblioteca, e se necessário \fCrelatar um problema\fP\&. Dúvidas e sugestões, me contate por mensagem ou por e-mail em danppoltronieri@gmail.com\&.
.PP
Veja o \fBguia de contribuição\fP!
.PP
.SS "Licensa"
.PP
[MIT © Richard McRichface\&.](LICENSE) 
