.TH "md__r_e_a_d_m_e" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Canary Project 
\fC\fP \fC\fP \fC\fP \fC\fP \fC\fP
.PP
\fBVersão em Português\&.\fP
.PP
The \fBCanary Project\fP is a mobile ambient monitoring device developed in Arduino and written in C++ with a companion app to be developed for Android and iOS\&. Its goal is to monitor air quality through the measurement of air pollutants, temperature, humidity and sound pollution levels\&.
.PP
.SS "Table of Contents"
.PP
.IP "\(bu" 2
\fCBackground\fP
.IP "\(bu" 2
\fCInstall\fP
.IP "\(bu" 2
\fCUsage\fP
.IP "\(bu" 2
\fCContribute\fP
.IP "\(bu" 2
\fCLicense\fP
.PP
.PP
.SS "Background"
.PP
This project started in February 2017 as my graduation thesis\&.
.PP
.SS "Install"
.PP
TODO
.PP
.SS "Usage"
.PP
TODO
.PP
.SS "Contribute"
.PP
TODO
.PP
Feel free to copy and improve this library, if necessary, you may \fCreport a problem\fP\&. Doubts and suggestions, contact me at danppoltronieri@gmail.com\&.
.PP
See \fBthe contribute file\fP!
.PP
PRs accepted\&.
.PP
.SS "License"
.PP
[GNU AGPL V3\&.](LICENSE) 
