.TH "md__backup__h_c05-master__r_e_a_d_m_e" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__backup__h_c05-master__r_e_a_d_m_e \- \fBHC05\fP 
An Arduino library for the HC-05 Bluetooth ITead Studio HC-05 Serial Port Module\&.
.PP
See the \fCLICENSE\fP file for copyright and license information\&.
.PP
The serial port can be configured as any supported Serial port or a SoftwareSerial port\&.
.PP
Includes a demonstration program that can be uses to change the name reported by an HC-05 module\&.
.PP
Additional information is available as an \fCexercise\fP at \fCRockingD Labs\fP\&.
.PP
.SS "Components "
.PP
\fC\fBHC05\fP\fP A class for controlling and communicating through an ITead Studio HC-05 Serial Port Module\&. This class inherits from the Stream class\&.
.PP
.SS "Methods:"
.PP
The Stream class is extended with the following methods\&.
.PP
\fCfindBaud()\fP Determine HC-05 communications speed\&. Make this call in \fBsetup()\fP instead of \fCbegin()\fP\&. \fCbegin()\fP is still avaialble and can be used inplace of \fCfindBaud()\fP if you know the HC-05 communications speed\&.
.PP
\fCsetBaud(unsigned long rate)\fP Specify the HC-05 communications speed\&. The speed is non-volatile so call this only when the rate returned by findBaud() is not the one you require\&.
.PP
\fCsetBaud(unsigned long rate, unsigned long parity, unsigned long stopbits)\fP Use this method when you need something besides the default no parity, one stop bit settings that are the default\&. \fBCAUTION!\fP The HC-05 supports many serial configurations that are not compatible with an Arduino\&. For example, the Arduino software serial port port supports only no parity, one stop bit settings\&.
.PP
\fCcmd()\fP Send a command to the module\&. The 'key' (cmdPin) pin is activated to put the module in command mode where 'AT' commands are recognized\&.
.PP
\fCcmdMode2Start(int pwrPin)\fP This is an alternate command mode\&. This 2nd command mode has the advantage forcing the HC-05 into a know communications speed: 38400\&. However, entering this 2nd command mode requires switching the power to the HC-05\&.
.PP
\fCcmdMode2End()\fP Exits the alternate command mode, leaving the power to the HC-05 on\&.
.PP
\fCconnected()\fP (Only if HC05_STATE_PIN is defined in \fC\fBHC05\&.h\fP\fP) Returns true when a BT connection has been established\&.
.PP
\fCwrite()\fP \fCprint*()\fP The write(), and print*(), methods block until there is a BT connection\&.
.PP
.SS "Example Programs "
.PP
The default library configuration uses a software serial port\&. The example programs will work with either a hardware or a software serial port\&. The configuration is changed by modifying the \fC\fBHC05\&.h\fP\fP file\&.
.PP
See the \fCSoftwareSerial\&.fzz\fP file for the proper default connections\&. (\fC\&.fzz\fP files can be read by the free program available from \fCFritzing\fP)
.PP
\fCchangeName\fP This application is one of the reasons I wrote this library\&. I wanted to be able to change the name reported by the HC-05 because I have multiple HC-05 modules that I kept mixing up\&. With this program you can set the name of the HC-05 module to reflect something physically identifying (or anything else that helps you tell your modules apart)\&.
.PP
\fCecho\fP Echo characters as they are received\&.
.PP
\fChc05_test\fP Tests the disconnect command (AT+DISC)\&. This was something I used during development and probably is not of general interest\&.
.PP
\fCrecover\fP This example used the 2nd command mode to \fIrecover\fP the HC-05 when its serial port settings are incompatible with the Arduino serial ports\&. Power to HC-05 must be controlled by an Arduino pin\&. See the \fCRecovery\&.fzz\fP diagram for suitable connections\&.
.PP
\fCfindBaudTest\fP Tests both setBaud() and findBaud() by trying every combination of supported rates\&. The output from this example looks best if DEBUG_HC05 is not defined\&. (Simply comment out that line in \fBHC05\&.h\fP)\&.
.PP
.SS "Installation "
.PP
.SS "Option 1: Git (Recommended)"
.PP
.IP "\(bu" 2
Follow this \fCGitHub repository\fP and use \fCgit\fP to track your own changes by cloning:
.PP
$ cd ~/sketchbook/libraries $ git clone https://github.com/jdunmire/HC05.git
.IP "\(bu" 2
Start the Arduino IDE and you should find \fC\fBHC05\fP\fP in the libraries section\&.
.PP
.PP
.SS "Option 2: Source only"
.PP
.IP "\(bu" 2
Download a ZIP file\&. The ZIP button at \fCGitHub\fP will always get the latest version, but you may prefer one of the \fCtagged\fP versions\&.
.IP "\(bu" 2
Unpack the zip file into your sketchbook library directory (\fC~/sketchbook/libraries\fP on Linux)\&.
.IP "\(bu" 2
Rename the resulting directory (or create a symlink) to ~/sketchbook/libraries/HC05
.IP "\(bu" 2
Start the Arduino IDE and you should find \fC\fBHC05\fP\fP in the libraries section\&.
.PP
.PP
.SS "Configuration"
.PP
By default the library is configured for a software serial port and debugging output to the hardware serial port (Serial) is turned on\&. You will need to edit the \fBHC05\&.h\fP file if you want to change those settings\&.
.PP
See the \fCSoftwareSerial\&.fzz\fP file for the proper default connections\&. The \fCHardwareSerial\&.fzz\fP shows the hardware port alternative\&. The files can be read by the free program available from \fCFritzing\fP
.PP
The Bluetooth port is \fCbtSerial\fP and must be setup as shown at the top of the Example sketches\&. If debugging output is enabled in \fBHC05\&.h\fP (it is by default) then your sketch must include a \fBDEBUG_BEGIN(baud)\fP command to initialize the debug output port and set it's baud rate\&.
.PP
.SS "Hardware Serial Port Issues for UNO"
.PP
Using the hardware serial port on the UNO comes with some caveats:
.PP
.IP "\(bu" 2
You will have to disconnect the HC-05 module to upload a sketch\&.
.IP "\(bu" 2
If you use the Arduino \fCSerial Monitor\fP you will see the traffic to and from the HC-05 serial port\&. If you type in the \fCSerial Monitor\fP it will interfere with the HC-05 traffic\&. 
.PP

