.TH "md__backup__m_q135-_arduino-_sensor-master__r_e_a_d_m_e" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__backup__m_q135-_arduino-_sensor-master__r_e_a_d_m_e \- MQ-135 Air Quality / Gas Sensor 
This code compatible with severals Arduino Board
.PP
Original Articles: https://hackaday.io/project/3475-sniffing-trinket/log/12363-mq135-arduino-library
.br
 MQ-135 Library: https://github.com/ckalpha/MQ135
.br
 Author: Damrongwit Nusuk
.br
 Email: jack@racksync.com
.br
 Visit Website: http://www.racksync.com
.br
 Website : http://www.racksync.com
.br
.PP
 
