.TH "md_lib__r_t_c__r_e_a_d_m_e" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_lib__r_t_c__r_e_a_d_m_e \- Rtc 
Arduino Real Time Clock library\&. An RTC library with deep device support\&.
.PP
\fC\fP.PP
Now supports esp8266\&. Now supports SoftwareWire library\&.
.PP
For quick questions jump on Gitter and ask away\&. \fC\fP
.PP
For bugs, make sure there isn't an active issue and then create one\&.
.PP
.SS "Documentation"
.PP
\fCSee Wiki\fP
.PP
.SS "Installing This Library (prefered, you just want to use it)"
.PP
Open the Library Manager and search for 'Rtc by Makuna' and install
.PP
.SS "Installing This Library From GitHub (advanced, you want to contribute)"
.PP
Create a directory in your Arduino folder named 'Rtc' Clone (Git) this project into that folder\&. It should now show up in the import list when you restart Arduino IDE\&. 
