.TH "Backup/MQ135/MQ135.cpp" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backup/MQ135/MQ135.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'MQ135\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
G\&.Krocker (Mad Frog Labs)  GNU GPLv3
.RE
.PP
First version of an Arduino Library for the \fBMQ135\fP gas sensor TODO: Review the correction factor calculation\&. This currently relies on the datasheet but the information there seems to be wrong\&.
.SH "HISTORY"
.PP
v1\&.0 - First release 
.PP
Definition in file \fBMQ135\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
