.TH "Backup/test/mq2misterio/MQ2.h" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backup/test/mq2misterio/MQ2.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'WProgram\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMQ2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
