.TH "MQ3" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MQ3 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MQSensor\&.hpp>\fP
.PP
Inherits \fBMQSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMQ3\fP (const uint8_t mqpin)"
.br
.ti -1c
.RI "float * \fBread\fP (bool print)"
.br
.ti -1c
.RI "float const \fBMQGetGasPercentage\fP (const float rs_ro_ratio, const uint8_t gas_id)"
.br
.ti -1c
.RI "float \fBreadC2H5OH\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 159 of file MQSensor\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MQ3::MQ3 (const uint8_t mqpin)"

.PP
Definition at line 247 of file MQSensor\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "float const MQ3::MQGetGasPercentage (const float rs_ro_ratio, const uint8_t gas_id)"

.PP
Definition at line 251 of file MQSensor\&.cpp\&.
.SS "float* MQ3::read (bool print)"

.SS "float MQ3::readC2H5OH ()"

.PP
Definition at line 256 of file MQSensor\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
