.TH "MQ4" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MQ4 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MQSensor\&.hpp>\fP
.PP
Inherits \fBMQSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMQ4\fP (const uint8_t mqpin)"
.br
.ti -1c
.RI "float * \fBread\fP (bool print)"
.br
.ti -1c
.RI "float const \fBMQGetGasPercentage\fP (const float rs_ro_ratio, const uint8_t gas_id)"
.br
.ti -1c
.RI "float \fBreadLPG\fP ()"
.br
.ti -1c
.RI "float \fBreadCO\fP ()"
.br
.ti -1c
.RI "float \fBreadSmoke\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 183 of file MQSensor\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MQ4::MQ4 (const uint8_t mqpin)"

.SH "Member Function Documentation"
.PP 
.SS "float const MQ4::MQGetGasPercentage (const float rs_ro_ratio, const uint8_t gas_id)"

.SS "float* MQ4::read (bool print)"

.SS "float MQ4::readCO ()"

.SS "float MQ4::readLPG ()"

.SS "float MQ4::readSmoke ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
