.TH "MQ7" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MQ7 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MQSensor\&.hpp>\fP
.PP
Inherits \fBMQSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMQ7\fP (const uint8_t mqpin)"
.br
.ti -1c
.RI "float \fBreadH2\fP ()"
.br
.ti -1c
.RI "float \fBreadCarbonMonoxide\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The class of the \fBMQ7\fP sensor, with it's relevant data\&.
.PP
\fBAuthor:\fP
.RS 4
Daniel Pereira Poltronieri 
.RE
.PP
\fBDate:\fP
.RS 4
October, 2017 Contact: danppoltronieri@gmail.com 
.RE
.PP

.PP
Definition at line 197 of file MQSensor\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MQ7::MQ7 (const uint8_t mqpin)"
\fBMQ7::MQ7\fP constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fImqpin\fP The arduino pin to which the sensor is connected\&. 
.RE
.PP

.PP
Definition at line 310 of file MQSensor\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "float MQ7::readCarbonMonoxide ()"
Checks if the current data is old, then proceeds to either checking the sensor for the current value or returns the stored value\&. 
.PP
\fBReturns:\fP
.RS 4
The most recent Carbon Monoxide data point\&. 
.RE
.PP

.PP
Definition at line 335 of file MQSensor\&.cpp\&.
.SS "float MQ7::readH2 ()"
Checks if the current data is old, then proceeds to either checking the sensor for the current value or returns the stored value\&. 
.PP
\fBReturns:\fP
.RS 4
The most recent H2 data point\&. 
.RE
.PP

.PP
Definition at line 321 of file MQSensor\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
