.TH "MQDummy" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MQDummy \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MQSensor\&.hpp>\fP
.PP
Inherits \fBMQSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMQDummy\fP (const uint8_t mqpin)"
.br
.ti -1c
.RI "uint16_t \fBcheck\fP (void)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fB_current_value\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is a dummy sensor, to be used to generate random values for debugging purposes\&.
.PP
\fBAuthor:\fP
.RS 4
Daniel Pereira Poltronieri 
.RE
.PP
\fBDate:\fP
.RS 4
October, 2017 Contact: danppoltronieri@gmail.com 
.RE
.PP

.PP
Definition at line 121 of file MQSensor\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MQDummy::MQDummy (const uint8_t mqpin)"

.PP
Definition at line 261 of file MQSensor\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "uint16_t MQDummy::check (void)\fC [inline]\fP"

.PP
Definition at line 127 of file MQSensor\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t MQDummy::_current_value\fC [protected]\fP"

.PP
Definition at line 134 of file MQSensor\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
