.TH "MQPotentiometer" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MQPotentiometer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MQSensor\&.hpp>\fP
.PP
Inherits \fBMQSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMQPotentiometer\fP (const uint8_t mqpin)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This uses a potentiometer as a sensor, to be used to generate values for debugging purposes\&. May be of better use if expandanded to handle a gas curve\&.
.PP
\fBAuthor:\fP
.RS 4
Daniel Pereira Poltronieri 
.RE
.PP
\fBDate:\fP
.RS 4
October, 2017 Contact: danppoltronieri@gmail.com 
.RE
.PP

.PP
Definition at line 150 of file MQSensor\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MQPotentiometer::MQPotentiometer (const uint8_t mqpin)"

.PP
Definition at line 270 of file MQSensor\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
