.TH "lib/MQ-Sensor/src/MQSensor.hpp" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/MQ-Sensor/src/MQSensor.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMQSensor\fP"
.br
.ti -1c
.RI "class \fBMQDummy\fP"
.br
.ti -1c
.RI "class \fBMQPotentiometer\fP"
.br
.ti -1c
.RI "class \fBMQ3\fP"
.br
.ti -1c
.RI "class \fBMQ7\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSENSOR_TYPE\fP : const uint8_t "
.br
.ti -1c
.RI "enum \fBGAS_TYPE\fP : const uint8_t "
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBGAS_TYPE\fP : const uint8_t"

.PP
Definition at line 29 of file MQSensor\&.hpp\&.
.SS "enum \fBSENSOR_TYPE\fP : const uint8_t"

.PP
Definition at line 15 of file MQSensor\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
