.TH "Pachube" 3 "Wed Jul 5 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pachube \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($api)"
.br
.ti -1c
.RI "\fBupdatePachube\fP ($url='', $data='')"
.br
.ti -1c
.RI "\fBupdatePachubeDatastream\fP ($feed='', $datastream='', $value='')"
.br
.ti -1c
.RI "\fBretrieveData\fP ($url='', $type='')"
.br
.ti -1c
.RI "\fBretrieveHistory\fP ($url='')"
.br
.ti -1c
.RI "\fBcreateFeed\fP ($title='')"
.br
.ti -1c
.RI "\fBdeletePachube\fP ($feed_id='')"
.br
.ti -1c
.RI "\fBdebugStatusCode\fP ($status_code)"
.br
.ti -1c
.RI "\fBshowGraph\fP ($feed_id='', $datastream_id, $width='300', $height='200', $colour='FF0066', $label=true, $grid=true, $title='', $legend='', $stroke='4')"
.br
.ti -1c
.RI "\fBgetLatLon\fP ($search='')"
.br
.ti -1c
.RI "\fBenvironment\fP ($feed_id)"
.br
.ti -1c
.RI "\fBshowEnvironmentGraph\fP ($\fBenvironment\fP, $datastream_id, $width='300', $height='200', $colour='FF0066', $label=true, $grid=true, $title='', $legend='', $stroke='4')"
.br
.ti -1c
.RI "\fBshowEnvironmentMap\fP ($\fBenvironment\fP, $width, $height, $google_map_key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file pachube_functions\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Pachube::__construct ( $api)"

.PP
Definition at line 43 of file pachube_functions\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "Pachube::createFeed ( $title = \fC''\fP)"

.PP
Definition at line 153 of file pachube_functions\&.php\&.
.SS "Pachube::debugStatusCode ( $status_code)"

.PP
Definition at line 202 of file pachube_functions\&.php\&.
.SS "Pachube::deletePachube ( $feed_id = \fC''\fP)"

.PP
Definition at line 177 of file pachube_functions\&.php\&.
.SS "Pachube::environment ( $feed_id)"

.PP
Definition at line 493 of file pachube_functions\&.php\&.
.SS "Pachube::getLatLon ( $search = \fC''\fP)"

.PP
Definition at line 262 of file pachube_functions\&.php\&.
.SS "Pachube::retrieveData ( $url = \fC''\fP,  $type = \fC''\fP)"

.PP
Definition at line 99 of file pachube_functions\&.php\&.
.SS "Pachube::retrieveHistory ( $url = \fC''\fP)"

.PP
Definition at line 128 of file pachube_functions\&.php\&.
.SS "Pachube::showEnvironmentGraph ( $environment,  $datastream_id,  $width = \fC'300'\fP,  $height = \fC'200'\fP,  $colour = \fC'FF0066'\fP,  $label = \fCtrue\fP,  $grid = \fCtrue\fP,  $title = \fC''\fP,  $legend = \fC''\fP,  $stroke = \fC'4'\fP)"

.PP
Definition at line 502 of file pachube_functions\&.php\&.
.SS "Pachube::showEnvironmentMap ( $environment,  $width,  $height,  $google_map_key)"

.PP
Definition at line 510 of file pachube_functions\&.php\&.
.SS "Pachube::showGraph ( $feed_id = \fC''\fP,  $datastream_id,  $width = \fC'300'\fP,  $height = \fC'200'\fP,  $colour = \fC'FF0066'\fP,  $label = \fCtrue\fP,  $grid = \fCtrue\fP,  $title = \fC''\fP,  $legend = \fC''\fP,  $stroke = \fC'4'\fP)"

.PP
Definition at line 242 of file pachube_functions\&.php\&.
.SS "Pachube::updatePachube ( $url = \fC''\fP,  $data = \fC''\fP)"

.PP
Definition at line 58 of file pachube_functions\&.php\&.
.SS "Pachube::updatePachubeDatastream ( $feed = \fC''\fP,  $datastream = \fC''\fP,  $value = \fC''\fP)"

.PP
Definition at line 77 of file pachube_functions\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
