.TH "RtcDS1307< T_WIRE_METHOD >" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RtcDS1307< T_WIRE_METHOD > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RtcDS1307\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRtcDS1307\fP (T_WIRE_METHOD &wire)"
.br
.ti -1c
.RI "void \fBBegin\fP ()"
.br
.ti -1c
.RI "bool \fBIsDateTimeValid\fP ()"
.br
.ti -1c
.RI "bool \fBGetIsRunning\fP ()"
.br
.ti -1c
.RI "void \fBSetIsRunning\fP (bool isRunning)"
.br
.ti -1c
.RI "void \fBSetDateTime\fP (const \fBRtcDateTime\fP &dt)"
.br
.ti -1c
.RI "\fBRtcDateTime\fP \fBGetDateTime\fP ()"
.br
.ti -1c
.RI "void \fBSetMemory\fP (uint8_t memoryAddress, uint8_t value)"
.br
.ti -1c
.RI "uint8_t \fBGetMemory\fP (uint8_t memoryAddress)"
.br
.ti -1c
.RI "uint8_t \fBSetMemory\fP (uint8_t memoryAddress, const uint8_t *pValue, uint8_t countBytes)"
.br
.ti -1c
.RI "uint8_t \fBGetMemory\fP (uint8_t memoryAddress, uint8_t *pValue, uint8_t countBytes)"
.br
.ti -1c
.RI "void \fBSetSquareWavePin\fP (\fBDS1307SquareWaveOut\fP pinMode)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T_WIRE_METHOD>
.br
class RtcDS1307< T_WIRE_METHOD >"

.PP
Definition at line 43 of file RtcDS1307\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T_WIRE_METHOD> \fBRtcDS1307\fP< T_WIRE_METHOD >::\fBRtcDS1307\fP (T_WIRE_METHOD & wire)\fC [inline]\fP"

.PP
Definition at line 46 of file RtcDS1307\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T_WIRE_METHOD> void \fBRtcDS1307\fP< T_WIRE_METHOD >::Begin ()\fC [inline]\fP"

.PP
Definition at line 51 of file RtcDS1307\&.h\&.
.SS "template<class T_WIRE_METHOD> \fBRtcDateTime\fP \fBRtcDS1307\fP< T_WIRE_METHOD >::GetDateTime ()\fC [inline]\fP"

.PP
Definition at line 100 of file RtcDS1307\&.h\&.
.SS "template<class T_WIRE_METHOD> bool \fBRtcDS1307\fP< T_WIRE_METHOD >::GetIsRunning ()\fC [inline]\fP"

.PP
Definition at line 61 of file RtcDS1307\&.h\&.
.SS "template<class T_WIRE_METHOD> uint8_t \fBRtcDS1307\fP< T_WIRE_METHOD >::GetMemory (uint8_t memoryAddress)\fC [inline]\fP"

.PP
Definition at line 128 of file RtcDS1307\&.h\&.
.SS "template<class T_WIRE_METHOD> uint8_t \fBRtcDS1307\fP< T_WIRE_METHOD >::GetMemory (uint8_t memoryAddress, uint8_t * pValue, uint8_t countBytes)\fC [inline]\fP"

.PP
Definition at line 161 of file RtcDS1307\&.h\&.
.SS "template<class T_WIRE_METHOD> bool \fBRtcDS1307\fP< T_WIRE_METHOD >::IsDateTimeValid ()\fC [inline]\fP"

.PP
Definition at line 56 of file RtcDS1307\&.h\&.
.SS "template<class T_WIRE_METHOD> void \fBRtcDS1307\fP< T_WIRE_METHOD >::SetDateTime (const \fBRtcDateTime\fP & dt)\fC [inline]\fP"

.PP
Definition at line 80 of file RtcDS1307\&.h\&.
.SS "template<class T_WIRE_METHOD> void \fBRtcDS1307\fP< T_WIRE_METHOD >::SetIsRunning (bool isRunning)\fC [inline]\fP"

.PP
Definition at line 66 of file RtcDS1307\&.h\&.
.SS "template<class T_WIRE_METHOD> void \fBRtcDS1307\fP< T_WIRE_METHOD >::SetMemory (uint8_t memoryAddress, uint8_t value)\fC [inline]\fP"

.PP
Definition at line 120 of file RtcDS1307\&.h\&.
.SS "template<class T_WIRE_METHOD> uint8_t \fBRtcDS1307\fP< T_WIRE_METHOD >::SetMemory (uint8_t memoryAddress, const uint8_t * pValue, uint8_t countBytes)\fC [inline]\fP"

.PP
Definition at line 139 of file RtcDS1307\&.h\&.
.SS "template<class T_WIRE_METHOD> void \fBRtcDS1307\fP< T_WIRE_METHOD >::SetSquareWavePin (\fBDS1307SquareWaveOut\fP pinMode)\fC [inline]\fP"

.PP
Definition at line 188 of file RtcDS1307\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
