.TH "lib/RTC/src/RtcDS1307.h" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/RTC/src/RtcDS1307.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <RtcDateTime\&.h>\fP
.br
\fC#include 'RtcUtility\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRtcDS1307< T_WIRE_METHOD >\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDS1307SquareWaveOut\fP { \fBDS1307SquareWaveOut_1Hz\fP = 0b00010000, \fBDS1307SquareWaveOut_4kHz\fP = 0b00010001, \fBDS1307SquareWaveOut_8kHz\fP = 0b00010010, \fBDS1307SquareWaveOut_32kHz\fP = 0b00010011, \fBDS1307SquareWaveOut_High\fP = 0b10000000, \fBDS1307SquareWaveOut_Low\fP = 0b00000000 }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBDS1307_ADDRESS\fP = 0x68"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_REG_TIMEDATE\fP = 0x00"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_REG_STATUS\fP = 0x00"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_REG_CONTROL\fP = 0x07"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_REG_RAMSTART\fP = 0x08"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_REG_RAMEND\fP = 0x3f"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_REG_RAMSIZE\fP = \fBDS1307_REG_RAMEND\fP \- \fBDS1307_REG_RAMSTART\fP"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_REG_TIMEDATE_SIZE\fP = 7"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_RS0\fP = 0"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_RS1\fP = 1"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_SQWE\fP = 4"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_OUT\fP = 7"
.br
.ti -1c
.RI "const uint8_t \fBDS1307_CH\fP = 7"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDS1307SquareWaveOut\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDS1307SquareWaveOut_1Hz \fP\fP
.TP
\fB\fIDS1307SquareWaveOut_4kHz \fP\fP
.TP
\fB\fIDS1307SquareWaveOut_8kHz \fP\fP
.TP
\fB\fIDS1307SquareWaveOut_32kHz \fP\fP
.TP
\fB\fIDS1307SquareWaveOut_High \fP\fP
.TP
\fB\fIDS1307SquareWaveOut_Low \fP\fP
.PP
Definition at line 33 of file RtcDS1307\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const uint8_t DS1307_ADDRESS = 0x68"

.PP
Definition at line 11 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_CH = 7"

.PP
Definition at line 31 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_OUT = 7"

.PP
Definition at line 28 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_REG_CONTROL = 0x07"

.PP
Definition at line 16 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_REG_RAMEND = 0x3f"

.PP
Definition at line 18 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_REG_RAMSIZE = \fBDS1307_REG_RAMEND\fP \- \fBDS1307_REG_RAMSTART\fP"

.PP
Definition at line 19 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_REG_RAMSTART = 0x08"

.PP
Definition at line 17 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_REG_STATUS = 0x00"

.PP
Definition at line 15 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_REG_TIMEDATE = 0x00"

.PP
Definition at line 14 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_REG_TIMEDATE_SIZE = 7"

.PP
Definition at line 22 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_RS0 = 0"

.PP
Definition at line 25 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_RS1 = 1"

.PP
Definition at line 26 of file RtcDS1307\&.h\&.
.SS "const uint8_t DS1307_SQWE = 4"

.PP
Definition at line 27 of file RtcDS1307\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
