.TH "lib/RTC/src/RtcDateTime.h" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/RTC/src/RtcDateTime.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRtcDateTime\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint16_t \fBc_OriginYear\fP = 2000"
.br
.ti -1c
.RI "const uint32_t \fBc_Epoch32OfOriginYear\fP = 946684800"
.br
.ti -1c
.RI "const uint8_t c_daysInMonth[] \fBPROGMEM\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint32_t c_Epoch32OfOriginYear = 946684800"

.PP
Definition at line 7 of file RtcDateTime\&.h\&.
.SS "const uint16_t c_OriginYear = 2000"

.PP
Definition at line 6 of file RtcDateTime\&.h\&.
.SS "const uint8_t c_daysInMonth [] PROGMEM"

.PP
Definition at line 12 of file RtcDateTime\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
