.TH "lib/RTC/src/RtcDateTime.cpp" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/RTC/src/RtcDateTime.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/pgmspace\&.h>\fP
.br
\fC#include 'RtcDateTime\&.h'\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBStringToUint8\fP (const char *pString)"
.br
.ti -1c
.RI "template<typename T > T \fBDaysSinceFirstOfYear2000\fP (uint16_t year, uint8_t month, uint8_t dayOfMonth)"
.br
.ti -1c
.RI "template<typename T > T \fBSecondsIn\fP (T days, uint8_t hours, uint8_t minutes, uint8_t seconds)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t c_daysInMonth[] \fBPROGMEM\fP = { 31,28,31,30,31,30,31,31,30,31,30,31 }"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > T DaysSinceFirstOfYear2000 (uint16_t year, uint8_t month, uint8_t dayOfMonth)"

.PP
Definition at line 83 of file RtcDateTime\&.cpp\&.
.SS "template<typename T > T SecondsIn (T days, uint8_t hours, uint8_t minutes, uint8_t seconds)"

.PP
Definition at line 97 of file RtcDateTime\&.cpp\&.
.SS "uint8_t StringToUint8 (const char * pString)"

.PP
Definition at line 20 of file RtcDateTime\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const uint8_t c_daysInMonth [] PROGMEM = { 31,28,31,30,31,30,31,31,30,31,30,31 }"

.PP
Definition at line 12 of file RtcDateTime\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
