.TH "RtcDateTime" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RtcDateTime \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RtcDateTime\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRtcDateTime\fP (uint32_t secondsFrom2000=0)"
.br
.ti -1c
.RI "\fBRtcDateTime\fP (uint16_t year, uint8_t month, uint8_t dayOfMonth, uint8_t hour, uint8_t minute, uint8_t second)"
.br
.ti -1c
.RI "\fBRtcDateTime\fP (const char *date, const char *time)"
.br
.ti -1c
.RI "uint16_t \fBYear\fP () const "
.br
.ti -1c
.RI "uint8_t \fBMonth\fP () const "
.br
.ti -1c
.RI "uint8_t \fBDay\fP () const "
.br
.ti -1c
.RI "uint8_t \fBHour\fP () const "
.br
.ti -1c
.RI "uint8_t \fBMinute\fP () const "
.br
.ti -1c
.RI "uint8_t \fBSecond\fP () const "
.br
.ti -1c
.RI "uint8_t \fBDayOfWeek\fP () const "
.br
.ti -1c
.RI "uint32_t \fBTotalSeconds\fP () const "
.br
.ti -1c
.RI "uint64_t \fBTotalSeconds64\fP () const "
.br
.ti -1c
.RI "void \fBoperator+=\fP (uint32_t seconds)"
.br
.ti -1c
.RI "\fBoperator uint32_t\fP () const "
.br
.ti -1c
.RI "uint32_t \fBEpoch32Time\fP () const "
.br
.ti -1c
.RI "void \fBInitWithEpoch32Time\fP (uint32_t time)"
.br
.ti -1c
.RI "uint64_t \fBEpoch64Time\fP () const "
.br
.ti -1c
.RI "void \fBInitWithEpoch64Time\fP (uint64_t time)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fB_initWithSecondsFrom2000\fP (T secondsFrom2000)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fB_yearFrom2000\fP"
.br
.ti -1c
.RI "uint8_t \fB_month\fP"
.br
.ti -1c
.RI "uint8_t \fB_dayOfMonth\fP"
.br
.ti -1c
.RI "uint8_t \fB_hour\fP"
.br
.ti -1c
.RI "uint8_t \fB_minute\fP"
.br
.ti -1c
.RI "uint8_t \fB_second\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file RtcDateTime\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RtcDateTime::RtcDateTime (uint32_t secondsFrom2000 = \fC0\fP)"

.PP
Definition at line 14 of file RtcDateTime\&.cpp\&.
.SS "RtcDateTime::RtcDateTime (uint16_t year, uint8_t month, uint8_t dayOfMonth, uint8_t hour, uint8_t minute, uint8_t second)\fC [inline]\fP"

.PP
Definition at line 14 of file RtcDateTime\&.h\&.
.SS "RtcDateTime::RtcDateTime (const char * date, const char * time)"

.PP
Definition at line 40 of file RtcDateTime\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void RtcDateTime::_initWithSecondsFrom2000 (T secondsFrom2000)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 103 of file RtcDateTime\&.h\&.
.SS "uint8_t RtcDateTime::Day () const\fC [inline]\fP"

.PP
Definition at line 40 of file RtcDateTime\&.h\&.
.SS "uint8_t RtcDateTime::DayOfWeek () const"

.PP
Definition at line 102 of file RtcDateTime\&.cpp\&.
.SS "uint32_t RtcDateTime::Epoch32Time () const\fC [inline]\fP"

.PP
Definition at line 76 of file RtcDateTime\&.h\&.
.SS "uint64_t RtcDateTime::Epoch64Time () const\fC [inline]\fP"

.PP
Definition at line 86 of file RtcDateTime\&.h\&.
.SS "uint8_t RtcDateTime::Hour () const\fC [inline]\fP"

.PP
Definition at line 44 of file RtcDateTime\&.h\&.
.SS "void RtcDateTime::InitWithEpoch32Time (uint32_t time)\fC [inline]\fP"

.PP
Definition at line 80 of file RtcDateTime\&.h\&.
.SS "void RtcDateTime::InitWithEpoch64Time (uint64_t time)\fC [inline]\fP"

.PP
Definition at line 90 of file RtcDateTime\&.h\&.
.SS "uint8_t RtcDateTime::Minute () const\fC [inline]\fP"

.PP
Definition at line 48 of file RtcDateTime\&.h\&.
.SS "uint8_t RtcDateTime::Month () const\fC [inline]\fP"

.PP
Definition at line 36 of file RtcDateTime\&.h\&.
.SS "RtcDateTime::operator uint32_t () const\fC [inline]\fP"

.PP
Definition at line 70 of file RtcDateTime\&.h\&.
.SS "void RtcDateTime::operator+= (uint32_t seconds)\fC [inline]\fP"

.PP
Definition at line 63 of file RtcDateTime\&.h\&.
.SS "uint8_t RtcDateTime::Second () const\fC [inline]\fP"

.PP
Definition at line 52 of file RtcDateTime\&.h\&.
.SS "uint32_t RtcDateTime::TotalSeconds () const"

.PP
Definition at line 108 of file RtcDateTime\&.cpp\&.
.SS "uint64_t RtcDateTime::TotalSeconds64 () const"

.PP
Definition at line 114 of file RtcDateTime\&.cpp\&.
.SS "uint16_t RtcDateTime::Year () const\fC [inline]\fP"

.PP
Definition at line 32 of file RtcDateTime\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t RtcDateTime::_dayOfMonth\fC [protected]\fP"

.PP
Definition at line 98 of file RtcDateTime\&.h\&.
.SS "uint8_t RtcDateTime::_hour\fC [protected]\fP"

.PP
Definition at line 99 of file RtcDateTime\&.h\&.
.SS "uint8_t RtcDateTime::_minute\fC [protected]\fP"

.PP
Definition at line 100 of file RtcDateTime\&.h\&.
.SS "uint8_t RtcDateTime::_month\fC [protected]\fP"

.PP
Definition at line 97 of file RtcDateTime\&.h\&.
.SS "uint8_t RtcDateTime::_second\fC [protected]\fP"

.PP
Definition at line 101 of file RtcDateTime\&.h\&.
.SS "uint8_t RtcDateTime::_yearFrom2000\fC [protected]\fP"

.PP
Definition at line 96 of file RtcDateTime\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
