.TH "RtcTemperature" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RtcTemperature \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RtcTemperature\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRtcTemperature\fP (int8_t degrees, uint8_t fraction)"
.br
.ti -1c
.RI "float \fBAsFloat\fP ()"
.br
.ti -1c
.RI "int8_t \fBAsWholeDegrees\fP ()"
.br
.ti -1c
.RI "uint8_t \fBGetFractional\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int8_t \fBintegerDegrees\fP"
.br
.ti -1c
.RI "uint8_t \fBdecimalFraction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file RtcTemperature\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RtcTemperature::RtcTemperature (int8_t degrees, uint8_t fraction)\fC [inline]\fP"

.PP
Definition at line 10 of file RtcTemperature\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "float RtcTemperature::AsFloat ()\fC [inline]\fP"

.PP
Definition at line 16 of file RtcTemperature\&.h\&.
.SS "int8_t RtcTemperature::AsWholeDegrees ()\fC [inline]\fP"

.PP
Definition at line 23 of file RtcTemperature\&.h\&.
.SS "uint8_t RtcTemperature::GetFractional ()\fC [inline]\fP"

.PP
Definition at line 28 of file RtcTemperature\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t RtcTemperature::decimalFraction\fC [protected]\fP"

.PP
Definition at line 35 of file RtcTemperature\&.h\&.
.SS "int8_t RtcTemperature::integerDegrees\fC [protected]\fP"

.PP
Definition at line 34 of file RtcTemperature\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
