.TH "lib/RTC/src/RtcTemperature.h" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/RTC/src/RtcTemperature.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRtcTemperature\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
