.TH "lib/RTC/src/RtcUtility.cpp" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/RTC/src/RtcUtility.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <avr/pgmspace\&.h>\fP
.br
\fC#include 'RtcUtility\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBBcdToUint8\fP (uint8_t val)"
.br
.ti -1c
.RI "uint8_t \fBUint8ToBcd\fP (uint8_t val)"
.br
.ti -1c
.RI "uint8_t \fBBcdToBin24Hour\fP (uint8_t bcdHour)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint8_t BcdToBin24Hour (uint8_t bcdHour)"

.PP
Definition at line 21 of file RtcUtility\&.cpp\&.
.SS "uint8_t BcdToUint8 (uint8_t val)"

.PP
Definition at line 11 of file RtcUtility\&.cpp\&.
.SS "uint8_t Uint8ToBcd (uint8_t val)"

.PP
Definition at line 16 of file RtcUtility\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
