.TH "TinyGPSSpeed" 3 "Fri Oct 27 2017" "Canary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyGPSSpeed \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TinyGPS++\&.h>\fP
.PP
Inherits \fBTinyGPSDecimal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBknots\fP ()"
.br
.ti -1c
.RI "double \fBmph\fP ()"
.br
.ti -1c
.RI "double \fBmps\fP ()"
.br
.ti -1c
.RI "double \fBkmph\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 166 of file TinyGPS++\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double TinyGPSSpeed::kmph ()\fC [inline]\fP"

.PP
Definition at line 171 of file TinyGPS++\&.h\&.
.SS "double TinyGPSSpeed::knots ()\fC [inline]\fP"

.PP
Definition at line 168 of file TinyGPS++\&.h\&.
.SS "double TinyGPSSpeed::mph ()\fC [inline]\fP"

.PP
Definition at line 169 of file TinyGPS++\&.h\&.
.SS "double TinyGPSSpeed::mps ()\fC [inline]\fP"

.PP
Definition at line 170 of file TinyGPS++\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Canary from the source code\&.
